In [1]:
import pandas as pd
from glob import glob

# --------------------------------------------------------------
# Read single CSV file
# --------------------------------------------------------------``

single_file_acc = pd.read_csv('MetaMotion/A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv')

single_file_gyr = pd.read_csv('MetaMotion/A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv')

# --------------------------------------------------------------
# List all data in MetaMotion/MetaMotion
# --------------------------------------------------------------

files = sorted(glob('MetaMotion/*.csv')) 

len(files)

# --------------------------------------------------------------
# Extract features from filename
# --------------------------------------------------------------

data_path = 'MetaMotion/'
f = files[1]
participant = f.split("-")[0].replace(data_path,"")
label = f.split("-")[1]
category =  f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

df = pd.read_csv(f)

df['participant'] = participant
df['label'] = label
df['category'] = category


# --------------------------------------------------------------
# Read all files
# --------------------------------------------------------------

acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for i in files:
    participant = i.split("-")[0].replace(data_path,"")
    label = i.split("-")[1]
    category =  i.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

    df = pd.read_csv(i)

    df['participant'] = participant
    df['label'] = label
    df['category'] = category
   
    if "Accelerometer" in i:
        df['set'] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df,df])


    if "Gyroscope" in i:
        df['set'] = gyr_set
        gyr_set += 1
        gyr_df = pd.concat([gyr_df,df])

In [2]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy,1
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy,1
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy,1
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy,1
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
237,1547666063089,2019-01-16 20:14:23.089,18.96,0.012,0.596,0.815,E,squat,heavy,94
238,1547666063169,2019-01-16 20:14:23.169,19.04,0.009,0.528,0.821,E,squat,heavy,94
239,1547666063249,2019-01-16 20:14:23.249,19.12,0.015,0.554,0.746,E,squat,heavy,94
240,1547666063329,2019-01-16 20:14:23.329,19.20,0.006,0.574,0.824,E,squat,heavy,94
241,1547666063409,2019-01-16 20:14:23.409,19.28,0.015,0.588,0.826,E,squat,heavy,94

In [3]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23578 entries, 0 to 241
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  object
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participant   23578 non-null  object
 7   label         23578 non-null  object
 8   category      23578 non-null  object
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 2.0+ MB

In [4]:
pd.to_datetime(df["epoch (ms)"],unit="ms")

0     2019-01-16 19:14:03.834
1     2019-01-16 19:14:03.874
2     2019-01-16 19:14:03.914
3     2019-01-16 19:14:03.954
4     2019-01-16 19:14:03.994
                ...
487   2019-01-16 19:14:23.314
488   2019-01-16 19:14:23.354
489   2019-01-16 19:14:23.394
490   2019-01-16 19:14:23.434
491   2019-01-16 19:14:23.474
Name: epoch (ms), Length: 492, dtype: datetime64[ns]

In [5]:
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"],unit="ms")

In [6]:
acc_df.head(5)

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:10:08.431,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy,1

In [7]:
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"],unit="ms")

In [8]:
gyr_df.head()

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:10:08.351,1547219408351,2019-01-11T16:10:08.351,0.00,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,1547219408391,2019-01-11T16:10:08.391,0.04,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,1547219408431,2019-01-11T16:10:08.431,0.08,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1547219408471,2019-01-11T16:10:08.471,0.12,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1547219408511,2019-01-11T16:10:08.511,0.16,1.524,-2.561,-2.500,A,bench,heavy,1

In [9]:
del acc_df["epoch (ms)"]
del acc_df["time (01:00)"]
del acc_df["elapsed (s)"]

del gyr_df["epoch (ms)"]
del gyr_df["time (01:00)"]
del gyr_df["elapsed (s)"]

In [10]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94

In [11]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.351,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,-1.707,-0.671,1.585,E,squat,heavy,93
2019-01-16 19:14:23.354,0.915,0.305,2.988,E,squat,heavy,93
2019-01-16 19:14:23.394,5.854,-2.561,1.463,E,squat,heavy,93
2019-01-16 19:14:23.434,4.268,0.549,-0.305,E,squat,heavy,93
2019-01-16 19:14:23.474,-1.098,1.768,-0.122,E,squat,heavy,93

In [12]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.511,0.000,0.961,-0.069,A,bench,heavy,1
2019-01-11 15:10:08.591,0.001,0.974,-0.087,A,bench,heavy,1
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,A,bench,heavy,1
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94

In [13]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:10:08.351,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1.524,-2.561,-2.500,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.314,-1.707,-0.671,1.585,E,squat,heavy,93
2019-01-16 19:14:23.354,0.915,0.305,2.988,E,squat,heavy,93
2019-01-16 19:14:23.394,5.854,-2.561,1.463,E,squat,heavy,93
2019-01-16 19:14:23.434,4.268,0.549,-0.305,E,squat,heavy,93
2019-01-16 19:14:23.474,-1.098,1.768,-0.122,E,squat,heavy,93

In [14]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df],axis=1)

In [15]:
data_merged

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
data_merged.dropna()

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,2.622,-8.110,-4.024,A,bench,heavy,1.0
2019-01-11 15:10:08.511,0.000,0.961,-0.069,1.524,-2.561,-2.500,A,bench,heavy,1.0
2019-01-11 15:10:08.591,0.001,0.974,-0.087,1.707,-5.366,0.915,A,bench,heavy,1.0
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,2.683,-4.146,-1.220,A,bench,heavy,1.0
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,1.524,0.610,-3.171,A,bench,heavy,1.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-15 19:04:25.561,0.369,0.591,0.761,11.220,-5.061,-5.061,A,squat,heavy,24.0
2019-01-15 19:04:25.641,0.387,0.566,0.776,3.963,-2.988,-0.793,A,squat,heavy,24.0
2019-01-15 19:04:25.721,0.361,0.574,0.680,15.305,-3.293,-0.671,A,squat,heavy,24.0
2019-01-15 19:04:25.801,0.353,0.583,0.635,30.366,-0.122,-4.573,A,squat,heavy,24.0
2019-01-15 19:04:25.881,0.359,0.605,0.678,14.756,-6.585,-2.378,A,squat,heavy,24.0

In [17]:
data_merged.columns = [
    "acc_x",
    "acc_y",
    "acc_z",
    "gyr_x",
    "gyr_y",
    "gyr_z",
    "participant",
    "label",
    "category",
    "set"
]

In [18]:
data_merged.columns

Index(['acc_x', 'acc_y', 'acc_z', 'gyr_x', 'gyr_y', 'gyr_z', 'participant',
       'label', 'category', 'set'],
      dtype='object')

In [19]:
sampling = {
    'acc_x':"mean", 
    'acc_y':"mean", 
    'acc_z':"mean",
    'gyr_x':"mean", 
    'gyr_y':"mean", 
    'gyr_z':"mean",
    'participant':"last",
    'label':"last", 
    'category':"last",
    'set':"last",
}

In [20]:
numeric_columns = data_merged.select_dtypes(include=['int64', 'float64']).columns

In [21]:
data_merged[:1000].resample(rule = "200ms").apply(sampling)

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.800,NaN,NaN,NaN,-9.69550,-1.7985,4.5735,B,bench,heavy,30.0
2019-01-11 15:08:05.000,NaN,NaN,NaN,-2.01220,-0.4270,-1.6218,B,bench,heavy,30.0
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.89040,2.4392,0.9388,B,bench,heavy,30.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.68260,-0.8904,2.1708,B,bench,heavy,30.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.56080,-0.2560,-1.4146,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-11 15:10:21.600,-0.174000,1.092667,-0.153333,-4.96360,-16.4026,21.9026,A,bench,heavy,1.0
2019-01-11 15:10:21.800,-0.219500,1.402500,-0.109000,-7.52440,18.6706,-22.6828,A,bench,heavy,1.0
2019-01-11 15:10:22.000,-0.192000,0.871667,-0.155667,2.60980,8.7070,-14.8658,A,bench,heavy,1.0
2019-01-11 15:10:22.200,-0.227000,0.891000,-0.170000,5.39020,4.0000,-0.3780,A,bench,heavy,1.0
2019-01-11 15:10:22.400,-0.225500,0.919500,-0.205500,6.34125,0.5795,9.9085,A,bench,heavy,1.0

In [22]:
days = [g for n, g in data_merged.groupby(pd.Grouper(freq = "D"))]

In [23]:
data_resampled = pd.concat([df.resample(rule = "200ms").apply(sampling).dropna() for df in days ])

In [24]:
data_resampled.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyr_x        9009 non-null   float64
 4   gyr_y        9009 non-null   float64
 5   gyr_z        9009 non-null   float64
 6   participant  9009 non-null   object
 7   label        9009 non-null   object
 8   category     9009 non-null   object
 9   set          9009 non-null   float64
dtypes: float64(7), object(3)
memory usage: 774.2+ KB

In [25]:
data_resampled["set"] = data_resampled["set"].astype(int)

In [26]:
data_resampled.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyr_x        9009 non-null   float64
 4   gyr_y        9009 non-null   float64
 5   gyr_z        9009 non-null   float64
 6   participant  9009 non-null   object
 7   label        9009 non-null   object
 8   category     9009 non-null   object
 9   set          9009 non-null   int64
dtypes: float64(6), int64(1), object(3)
memory usage: 774.2+ KB

In [27]:
data_resampled.to_pickle('MetaMotion/data_resampled.pkl')